# Generated by Django 2.2.7 on 2020-06-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200606_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='answer',
            field=models.ManyToManyField(null=True, to='questions.Choice'),
        ),
    ]
